---
version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre
    container_name: calibre
    env_file:
      - .env
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CALIBRE_CONFIG_FOLDER}:/config
      - ${CALIBRE_IMPORT_FOLDER}:/import
      - ./recipes:/recipes
      - ./crons/calibre-cron:/etc/cron.d/calibre-cron
      - ./scripts:/scripts
    ports:
      - 8780:8080
      - 8781:8081
      - 8782:9090
    restart: unless-stopped
    entrypoint: 
    - "/bin/bash"
    - "-c"
    - "chmod +x /scripts/init.sh && /scripts/init.sh"
  calibre-web:
    depends_on:
      - calibre
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${CALIBRE_CONFIG_FOLDER}:/config
      - ${CALIBRE_IMPORT_FOLDER}:/books
    ports:
      - 8783:8083
    restart: unless-stopped