---
version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre
    container_name: calibre
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/externalssd/calibre/config:/config
      - /srv/externalssd/downloads/Books/complete:/import
      - ./recipes:/recipes
    ports:
      - 8780:8080
      - 8781:8081
      - 8782:9090
    restart: unless-stopped
