---
version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre
    container_name: calibre
    env_file:
      - .env
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/externalssd/calibre/config:/config
      - /srv/externalssd/downloads/Books/complete:/import
      - ./recipes:/recipes
      - ./crons/calibre-cron:/etc/cron.d/calibre-cron
      - ./scripts:/scripts
    ports:
      - 8780:8080
      - 8781:8081
      - 8782:9090
    restart: unless-stopped
    entrypoint: 
    - "/bin/bash"
    - "-c"
    - "chmod +x /scripts/init.sh && /scripts/init.sh"